apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: audio-qa
spec:
  name: audio-qa
  annotations:
    seldon.io/engine-separate-pod: "true"
  protocol: v2
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/audio-qa-pipelines-mlserver:audio
          name: audio
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: facebook/s2t-small-librispeech-asr
            - name: TRANSFORMERS_CACHE
              value: /app/.cache
            - name: TASK
              value: automatic-speech-recognition
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
    - spec:
        containers:
        - image: gcr.io/hale-ivy-335012/audio-qa-pipelines-mlserver:nlpqa
          name: nlp-qa
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: distilbert-base-uncased
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: TASK
              value: question-answering
            - name: CONTEXT
              value: default
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
    graph:
      name: audio
      type: MODEL
      children:
      - name: nlp-qa
        type: MODEL
        children: []
    name: example
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1
