apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: cascade-dummy
spec:
  name: cascade-dummy
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/combiner:combiner
          name: combiner
          imagePullPolicy: Always
    - spec:
        containers:
        - image: sdghafouri/combiner:router
          name: router
          imagePullPolicy: Always
    - spec:
        containers:
        - image: sdghafouri/combiner:model1
          name: model1
          imagePullPolicy: Always
    - spec:
        containers:
        - image: sdghafouri/combiner:model2
          name: model2
          imagePullPolicy: Always
    - spec:
        containers:
        - image: sdghafouri/combiner:model2
          name: dummy
          imagePullPolicy: Always
    graph:
      name: combiner
      type: COMBINER
      children:
      - name: model2
        type: MODEL
        children:
          - name: router
            type: MODEL
            children:
            - name: model1
              type: MODEL
              children: []
      - name: dummy
        type: MODEL
        children:
          - name: router
            type: MODEL
            children:
            - name: model1
              type: MODEL
              children: []
    name: cascade-dummy
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1