apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: cascade-router
spec:
  name: cascade-router
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/combiner:router
          name: router
          imagePullPolicy: Always
    - spec:
        containers:
        - image: sdghafouri/combiner:model1
          name: model1
          imagePullPolicy: Always
    - spec:
        containers:
        - image: sdghafouri/combiner:model2
          name: model2
          imagePullPolicy: Always
    graph:
      name: model1
      type: MODEL
      children:
        - name: router
          type: ROUTER
          children:
            - name: model2
              type: MODEL
              children: []
    name: cascade-router
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1