apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
<<<<<<< HEAD
  name: multi
spec:
  name: default
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: multi
        - annotations:
          seldon.io/no-engine: "true"

=======
<<<<<<< HEAD:pipelines/18-models-proof-concept-triton/resnet.yaml
  name: resnet
=======
  name: multi
>>>>>>> 2c730123a2996da74dd0bd978fd20cf37b5f2aa3:pipelines/15-triton-operations/seldon-triton-multi.yaml
spec:
  name: default
  predictors:
>>>>>>> 2c730123a2996da74dd0bd978fd20cf37b5f2aa3
  - graph:
      implementation: TRITON_SERVER
      logger:
        mode: all
<<<<<<< HEAD
      modelUri: s3://minio-seldon/models
      envSecretRefName: seldon-init-container-secret
      name: multi # This should have the same name as the model inside otherwise endpoint not accesible
=======
      modelUri: s3://minio-seldon/seldon
      envSecretRefName: seldon-init-container-secret
<<<<<<< HEAD:pipelines/18-models-proof-concept-triton/resnet.yaml
      name: resnet # This should have the same name as the model inside
=======
      name: multi # This should have the same name as the model inside otherwise endpoint not accesible
>>>>>>> 2c730123a2996da74dd0bd978fd20cf37b5f2aa3:pipelines/15-triton-operations/seldon-triton-multi.yaml
>>>>>>> 2c730123a2996da74dd0bd978fd20cf37b5f2aa3
      type: MODEL
    name: default
    replicas: 1
  protocol: kfserving
