apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: image-models
spec:
  name: default
  predictors:
  - graph:
      implementation: TRITON_SERVER
      logger:
        mode: all
      modelUri: s3://separate-servers/separate-servers
      envSecretRefName: seldon-init-container-secret
      name: image-models # This should have the same name as the model inside
      type: MODEL
    name: default
    replicas: 1
  protocol: kfserving
