apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: seldon-core
    seldon-app: yolo-yolo
    seldon-deployment-id: yolo
    seldon.io/model: "true"
  name: yolo-yolo
  namespace: default
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: grpc
    port: 9500
    protocol: TCP
    targetPort: 9500
  selector:
    seldon-app: yolo-yolo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
