apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: nlp-sum
spec:
  name: nlp-sum
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/sum-qa-pipelines:nlpsum
          name: nlp-1
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: sshleifer/distilbart-cnn-12-6
            - name: TRANSFORMERS_CACHE
              value: /app/.cache
            - name: TASK
              value: summarization
    graph:
      name: nlp-1
      type: MODEL
      children: []
    name: example
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1
