apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nlp
  template:
    metadata:
      labels:
        app: nlp
    spec:
      containers:
      - name: nlp
        image: sdghafouri/simple-image:nlp
        imagePullPolicy: Always
        env:
          - name: ITERATIONS
            value: '60'
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 1
        ports:
        - containerPort: 8080
