apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: nlp-qa-dummy
spec:
  protocol: v2
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
    - name: default
      componentSpecs:
        - spec:
            containers:
            - name: nlp-qa
              image: sdghafouri/sum-qa-pipelines-mlserver:nlpqa
              imagePullPolicy: Always
      graph:
        name: nlp-qa
        type: MODEL
        children: []

