apiVersion: v1
kind: PersistentVolume
metadata:
  name: torchhub-vol
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /fileshare/torchhub
    server: 192.5.86.160
