apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: triton-image
  name: triton-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: triton-image
  template:
    metadata:
      labels:
        app: triton-image
    spec:
      containers:
      - args:
        - -c
        - cp /var/run/secrets/kubernetes.io/serviceaccount/ca.crt /usr/local/share/ca-certificates
          && update-ca-certificates && /opt/tritonserver/bin/tritonserver --model-store=s3://http://minio.minio-system.svc.cluster.local:9000/triton-server-all-new/triton-server-all-new/
          --strict-model-config=False --model-control-mode=explicit
        command:
        - /bin/bash
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: AWS_ACCESS_KEY_ID
              name: aws-credentials
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: AWS_SECRET_ACCESS_KEY
              name: aws-credentials
        image: nvcr.io/nvidia/tritonserver:22.05-py3
        name: tritonserver
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: grpc
        - containerPort: 8002
          name: metrics
        resources:
          limits:
            cpu: 8
            nvidia.com/gpu: '0'
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
