apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: nlp-li
spec:
  protocol: v2
  name: nlp-li
  annotations:
    proxy.istio.io/config: |
      terminationDrainDuration: 10s
  predictors:
  - name: nlp-li
    annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - spec:
        volumes:
        - name: classifier-provision-location
          emptyDir: {}

        initContainers:
        - name: classifier-model-initializer
          image: seldonio/rclone-storage-initializer:1.16.0-dev
          imagePullPolicy: IfNotPresent
          args:
            - "s3://huggingface/text-classification/dinalzein-xlm-roberta-base-finetuned-language-identification"
            - "/mnt/models/dinalzein-xlm-roberta-base-finetuned-language-identification"

          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          envFrom:
          - secretRef:
              name: seldon-rclone-secret

        terminationGracePeriodSeconds: 10
        containers:
        - image: sdghafouri/nlp-centralized:nlpli
          name: nlp-li
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '8'
              memory: 4Gi
            limits:
              cpu: '8'
              memory: 4Gi
          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          env:
            - name: MODEL_VARIANT
              value: dinalzein-xlm-roberta-base-finetuned-language-identification
            # - name: TRANSFORMERS_CACHE
            #   value: /opt/mlserver/.cache
            - name: TASK
              value: text-classification
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
            - name: USE_THREADING
              value: "True"
            - name: NUM_INTEROP_THREADS
              value: "8"
            - name: NUM_THREADS
              value: "8"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - /bin/sleep 10
      replicas: 1
    graph:
      name: nlp-li
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"
---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: queue-nlp-li
spec:
  protocol: v2
  name: queue-nlp-li
  predictors:
  - name: queue-nlp-li
    annotations:
      seldon.io/no-engine: "true" 
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/queue:queue
          name: queue-nlp-li
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 8Gi
            limits:
              cpu: '16'
              memory: 16Gi
          env:
            - name: MODEL_NAME
              value: 'nlp-li'
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    graph:
      name: queue-nlp-li
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"

---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: nlp-sum
spec:
  protocol: v2
  name: nlp-sum
  annotations:
    proxy.istio.io/config: |
      terminationDrainDuration: 10s
  predictors:
  - name: nlp-sum
    annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - spec:
        volumes:
        - name: classifier-provision-location
          emptyDir: {}

        initContainers:
        - name: classifier-model-initializer
          image: seldonio/rclone-storage-initializer:1.16.0-dev
          imagePullPolicy: IfNotPresent
          args:
            - "s3://huggingface/summarization/sshleifer-distilbart-cnn-12-6"
            - "/mnt/models/sshleifer-distilbart-cnn-12-6"

          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          envFrom:
          - secretRef:
              name: seldon-rclone-secret

        terminationGracePeriodSeconds: 10
        containers:
        - image: sdghafouri/nlp-centralized:nlpsum
          name: nlp-sum
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '8'
              memory: 4Gi
            limits:
              cpu: '8'
              memory: 4Gi
          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          env:
            - name: MODEL_VARIANT
              value:  sshleifer-distilbart-cnn-12-6
            - name: TASK
              value: summarization
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
            - name: USE_THREADING
              value: "True"
            - name: NUM_INTEROP_THREADS
              value: "8"
            - name: NUM_THREADS
              value: "8"
            - name: MIN_LENGTH
              value: '0'
            - name: MAX_LENGTH
              value: '4'
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - /bin/sleep 10
      replicas: 1
    graph:
      name: nlp-sum
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"
---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: queue-nlp-sum
spec:
  protocol: v2
  name: queue-nlp-sum
  predictors:
  - name: queue-nlp-sum
    annotations:
      seldon.io/no-engine: "true" 
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/queue:queue
          name: queue-nlp-sum
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 8Gi
            limits:
              cpu: '16'
              memory: 16Gi
          env:
            - name: MODEL_NAME
              value: 'nlp-sum'
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    graph:
      name: queue-nlp-sum
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"

---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: nlp-trans
spec:
  protocol: v2
  name: nlp-trans
  annotations:
    proxy.istio.io/config: |
      terminationDrainDuration: 10s
  predictors:
  - name: nlp-trans
    annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - spec:
        volumes:
        - name: classifier-provision-location
          emptyDir: {}

        initContainers:
        - name: classifier-model-initializer
          image: seldonio/rclone-storage-initializer:1.16.0-dev
          imagePullPolicy: IfNotPresent
          args:
            - "s3://huggingface/translation_fr_to_en/Helsinki-NLP-opus-mt-fr-en"
            - "/mnt/models/Helsinki-NLP-opus-mt-fr-en"

          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          envFrom:
          - secretRef:
              name: seldon-rclone-secret

        terminationGracePeriodSeconds: 10
        containers:
        - image: sdghafouri/nlp-centralized:nlptrans
          name: nlp-trans
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '8'
              memory: 4Gi
            limits:
              cpu: '8'
              memory: 4Gi
          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          env:
            - name: MODEL_VARIANT
              value: Helsinki-NLP-opus-mt-fr-en
            - name: TASK
              value: translation_fr_to_en
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
            - name: USE_THREADING
              value: "True"
            - name: NUM_INTEROP_THREADS
              value: "8"
            - name: NUM_THREADS
              value: "8"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - /bin/sleep 10
      replicas: 1
    graph:
      name: nlp-trans
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"
---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: queue-nlp-trans
spec:
  protocol: v2
  name: queue-nlp-trans
  predictors:
  - name: queue-nlp-trans
    annotations:
      seldon.io/no-engine: "true" 
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/queue:queue
          name: queue-nlp-trans
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 8Gi
            limits:
              cpu: '16'
              memory: 16Gi
          env:
            - name: MODEL_NAME
              value: 'nlp-trans'
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    graph:
      name: queue-nlp-trans
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"
---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: router
spec:
  protocol: v2
  name: router
  predictors:
  - name: router
    annotations:
      seldon.io/no-engine: "true" 
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/router:router
          name: router
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '2'
              memory: 4Gi
            limits:
              cpu: '2'
              memory: 4Gi
          env:
            - name: MODEL_LISTS
              value: '["queue-nlp-li", "queue-nlp-sum", "queue-nlp-trans"]'
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    graph:
      name: router
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"
