apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: nlp-sum
spec:
  protocol: v2
  name: nlp-sum
  predictors:
  - name: nlp-sum
    annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - spec:

        volumes:
        - name: classifier-provision-location
          emptyDir: {}

        initContainers:
        - name: classifier-model-initializer
          image: seldonio/rclone-storage-initializer:1.16.0-dev
          imagePullPolicy: IfNotPresent
          args:
            - "s3://huggingface/summarization/sshleifer-distilbart-xsum-1-1"
            - "/mnt/models/sshleifer-distilbart-xsum-1-1"
            - "--ignore-checksum"

          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          envFrom:
          - secretRef:
              name: seldon-rclone-secret

        containers:
        - image: sdghafouri/sum-qa-centralized:nlpsum
          name: nlp-sum 
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 4Gi
            limits:
              cpu: '4'
          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          env:
            - name: MODEL_VARIANT
              value: sshleifer-distilbart-xsum-1-1
            - name: TASK
              value: summarization
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
            - name: USE_THREADING
              value: "True"
            - name: NUM_INTEROP_THREADS
              value: "4"
            - name: NUM_THREADS
              value: "4"
            - name: LOGS_ENABLED
              value: 'True'
            - name: MIN_LENGTH
              value: '0'
            - name: MAX_LENGTH
              value: '4'
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 10
    graph:
      name: nlp-sum
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"
---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: queue-nlp-sum
spec:
  protocol: v2
  name: queue-nlp-sum
  predictors:
  - name: queue-nlp-sum
    annotations:
      seldon.io/no-engine: "true" 
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/queue:queue
          name: queue-nlp-sum
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 4Gi
            limits:
              cpu: '4'
              memory: 4Gi
          env:
            - name: MODEL_NAME
              value: 'nlp-sum'
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
            - name: LOGS_ENABLED
              value: 'True'
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    graph:
      name: queue-nlp-sum
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"
---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: nlp-qa
spec:
  protocol: v2
  name: nlp-qa
  predictors:
  - name: nlp-qa
    annotations:
      seldon.io/no-engine: "true" 
    componentSpecs:
    - spec:

        volumes:
        - name: classifier-provision-location
          emptyDir: {}

        initContainers:
        - name: classifier-model-initializer
          image: seldonio/rclone-storage-initializer:1.16.0-dev
          imagePullPolicy: IfNotPresent
          args:
            - "s3://huggingface/question-answering/distilbert-base-cased-distilled-squad"
            - "/mnt/models/distilbert-base-cased-distilled-squad"

          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          envFrom:
          - secretRef:
              name: seldon-rclone-secret

        containers:
        - image: sdghafouri/sum-qa-centralized:nlpqa
          name: nlp-qa 
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 4Gi
            limits:
              cpu: '4'
              memory: 4Gi
          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          env:
            - name: MODEL_VARIANT
              value: distilbert-base-cased-distilled-squad
            - name: TASK
              value: question-answering
            - name: CONTEXT
              value: default
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
            - name: USE_THREADING
              value: "True"
            - name: NUM_INTEROP_THREADS
              value: "4"
            - name: NUM_THREADS
              value: "4"
            - name: LOGS_ENABLED
              value: 'True'
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 10
    graph:
      name: nlp-qa
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"
---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: queue-nlp-qa
spec:
  protocol: v2
  name: queue-nlp-qa
  predictors:
  - name: queue-nlp-qa
    annotations:
      seldon.io/no-engine: "true" 
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/queue:queue
          name: queue-nlp-qa
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 4Gi
            limits:
              cpu: '4'
              memory: 4Gi
          env:
            - name: MODEL_NAME
              value: 'nlp-qa'
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
            - name: LAST_NODE
              value: 'True'
            - name: LOGS_ENABLED
              value: 'True'
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    graph:
      name: queue-nlp-qa
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"
---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: router
spec:
  protocol: v2
  name: router
  predictors:
  - name: router
    annotations:
      seldon.io/no-engine: "true" 
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/router:router
          name: router
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '2'
              memory: 4Gi
            limits:
              cpu: '2'
              memory: 4Gi
          env:
            - name: MODEL_LISTS
              value: '["queue-nlp-sum", "queue-nlp-qa"]'
            - name: LOGS_ENABLED
              value: 'True'
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    graph:
      name: router
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"