apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: resnet-human
spec:
  protocol: v2
  name: resnet-human
  annotations:
    proxy.istio.io/config: |
      terminationDrainDuration: 10s
  predictors:
  - name: resnet-human
    annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - spec:

        # volumes:
        # - name: resnet-volume
        #   emptyDir: {}

        # initContainers:
        # - name: classifier-model-initializer
        #   image: seldonio/rclone-storage-initializer:1.16.0-dev
        #   imagePullPolicy: IfNotPresent
        #   args:
        #     - "s3://torchhub/resnet/resnet34"
        #     - "/opt/mlserver/.torch/hub/checkpoints/"

        #   volumeMounts:
        #   - mountPath: /opt/mlserver/.torch/hub/checkpoints
        #     name: resnet-volume

        #   envFrom:
        #   - secretRef:
        #       name: seldon-rclone-secret

        terminationGracePeriodSeconds: 10
        containers:
        - image: sdghafouri/video-centralized:resnet-human
          name: resnet-human
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '1'
              memory: 4Gi
            limits:
              cpu: '1'
              memory: 4Gi
          # volumeMounts:
          # - mountPath: /opt/mlserver/.torch/hub/checkpoints
          #   name: resnet-volume

          env:
            - name: MODEL_VARIANT
              value: resnet34
            - name: TORCH_HOME
              value: /opt/mlserver/.torch
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "32"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
            - name: USE_THREADING
              value: "True"
            - name: NUM_INTEROP_THREADS
              value: "1"
            - name: NUM_THREADS
              value: "1"
            - name: DROP_LIMIT
              value: "1000"
            - name: LOGS_ENABLED
              value: "False"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - /bin/sleep 10
      replicas: 1
    graph:
      name: resnet-human
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1