apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: router-router-0-router
    app.kubernetes.io/managed-by: seldon-core
    fluentd: "true"
    seldon-app: router-router
    seldon-app-svc-router: router-router-router
    seldon-deployment-id: router
    seldon.io/model: "true"
    sidecar.istio.io/inject: "true"
    version: router
  name: router-router-0-router
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: {{ replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      seldon-app: router-router
      seldon-app-svc-router: router-router-router
      seldon-deployment-id: router
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /prometheus
        prometheus.io/scrape: "true"
        seldon.io/no-engine: "true"
      creationTimestamp: null
      labels:
        app: router-router-0-router
        app.kubernetes.io/managed-by: seldon-core
        fluentd: "true"
        seldon-app: router-router
        seldon-app-svc-router: router-router-router
        seldon-deployment-id: router
        seldon.io/model: "true"
        sidecar.istio.io/inject: "true"
        version: router
    spec:
      containers:
      - env:
        - name: MLSERVER_PARALLEL_WORKERS
          value: "0"
        - name: DROP_LIMIT
          value: '{{drop_limit}}'
        - name: LOGS_ENABLED
          value: '{{ logs_enabled }}'
        - name: PREDICTIVE_UNIT_SERVICE_PORT
          value: "9000"
        - name: PREDICTIVE_UNIT_HTTP_SERVICE_PORT
          value: "9000"
        - name: MLSERVER_HTTP_PORT
          value: "9000"
        - name: PREDICTIVE_UNIT_GRPC_SERVICE_PORT
          value: "9500"
        - name: MLSERVER_GRPC_PORT
          value: "9500"
        - name: PREDICTIVE_UNIT_ID
          value: router
        - name: MLSERVER_MODEL_NAME
          value: router
        - name: PREDICTIVE_UNIT_IMAGE
          value: sdghafouri/dynainf:router
        - name: PREDICTOR_ID
          value: router
        - name: PREDICTOR_LABELS
          value: '{"sidecar.istio.io/inject":"true","version":"router"}'
        - name: SELDON_DEPLOYMENT_ID
          value: router
        - name: SELDON_EXECUTOR_ENABLED
          value: "true"
        - name: PREDICTIVE_UNIT_METRICS_SERVICE_PORT
          value: "6000"
        - name: PREDICTIVE_UNIT_METRICS_ENDPOINT
          value: /prometheus
        - name: MLSERVER_METRICS_PORT
          value: "6000"
        - name: MLSERVER_METRICS_ENDPOINT
          value: /prometheus
        image: sdghafouri/dynainf:router
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /bin/sleep {{ distrpution_time }}
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 1
        name: router
        ports:
        - containerPort: 6000
          name: metrics
          protocol: TCP
        - containerPort: 9000
          name: http
          protocol: TCP
        - containerPort: 9500
          name: grpc
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 1
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 1
        resources:
          requests:
            cpu: '{{ cpu_request }}'
            memory: '{{ memory_request }}'
          limits:
            cpu: '{{ cpu_limit }}'
            memory: '{{ memory_limit }}'
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/podinfo
          name: seldon-podinfo
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 8888
      terminationGracePeriodSeconds: {{ distrpution_time }}
      volumes:
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: seldon-podinfo

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: seldon-core
    seldon-app: router-router
    seldon-deployment-id: router
    seldon.io/model: "true"
  name: router-router
  namespace: default
spec:
  ports:
  - name: http
    # nodePort: 32002
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: grpc
    nodePort: 32001
    port: 9500
    protocol: TCP
    targetPort: 9500
  selector:
    seldon-app: router-router
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
