apiVersion: v1
kind: Service
metadata:
  annotations:
    seldon.io/no-engine: "true"
  creationTimestamp: "2024-02-01T15:14:24Z"
  labels:
    app.kubernetes.io/managed-by: seldon-core
    seldon-app: queue-queue
    seldon-deployment-id: queue
    seldon.io/model: "true"
  name: queue-queue
  namespace: default
  ownerReferences:
  - apiVersion: machinelearning.seldon.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: SeldonDeployment
    name: queue
    uid: 662ca036-fa25-4c7d-9d2b-18ceae444936
  resourceVersion: "4969491"
  selfLink: /api/v1/namespaces/default/services/queue-queue
  uid: a3d72ada-fc9d-4743-9b92-d934b5151797
spec:
  clusterIP: 10.152.183.70
  clusterIPs:
  - 10.152.183.70
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: grpc
    port: 9500
    protocol: TCP
    targetPort: 9500
  selector:
    seldon-app: queue-queue
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
