apiVersion: v1
kind: Service
metadata:
  annotations:
    seldon.io/no-engine: "true"
  creationTimestamp: "2024-02-01T15:14:24Z"
  labels:
    app.kubernetes.io/managed-by: seldon-core
    seldon-app: queue-queue
    seldon-app-svc-queue: queue-queue-queue
    seldon-deployment-id: queue
    seldon.io/model: "true"
  name: queue-queue-queue
  namespace: default
  ownerReferences:
  - apiVersion: machinelearning.seldon.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: SeldonDeployment
    name: queue
    uid: 662ca036-fa25-4c7d-9d2b-18ceae444936
  resourceVersion: "4969488"
  selfLink: /api/v1/namespaces/default/services/queue-queue-queue
  uid: 15b4964a-1200-410d-8713-d5a7b2964540
spec:
  clusterIP: 10.152.183.181
  clusterIPs:
  - 10.152.183.181
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: grpc
    port: 9500
    protocol: TCP
    targetPort: 9500
  selector:
    seldon-app-svc-queue: queue-queue-queue
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
