apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torchhub-claim
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: slow
  volumeName: torchhub-vol
