apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: mock-pipeline
spec:
  name: mock-pipeline
  annotations:
    seldon.io/engine-separate-pod: "true"
  protocol: v2
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/grpc-pipeline:node-one
          name: node-one
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '2'
              memory: 2Gi
            limits:
              cpu: '2'
              memory: 2Gi
          env:
            - name: MODEL_VARIANT
              value: "0"
            - name: MODEL_SYNC
              value: "True"
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "1"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "0"
      replicas: 1
    - spec:
        containers:
        - image: sdghafouri/grpc-pipeline:node-two
          name: node-two 
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '2'
              memory: 2Gi
            limits:
              cpu: '2'
              memory: 2Gi
          env:
            - name: MODEL_VARIANT
              value: "0"
            - name: MODEL_SYNC
              value: "True"
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "1"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "0"
      replicas: 1
    graph:
      name: node-one
      type: MODEL
      children:
      - name: node-two
        type: MODEL
        children: []
    svcOrchSpec:
      env:
      - name: SELDON_LOG_LEVEL
        value: DEBUG
      resources:
        requests:
          cpu: '2'
          memory: 2Gi
        limits:
          cpu: '2'
          memory: 2Gi
    name: example
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1
