apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: {{ model_name }}
spec:
  name: default
  predictors:
  - graph:
      implementation: TRITON_SERVER
      logger:
        mode: all
      modelUri: {{ model_uri }}
      envSecretRefName: seldon-init-container-secret
      name: {{ model_name }}
      type: MODEL
    name: default
    replicas: 1
  protocol: kfserving