apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      terminationGracePeriodSeconds: 20
      containers:
        - name: test-app
          image: alpine:3.14.2
          command: ["/bin/sh"]
          args: ["-c", "echo 'test-app is running'; sleep 3000"]
          # lifecycle:
          #   preStop:
          #     exec:
          #       command: ["/bin/sh", "-c", "echo 'test-app is stopping'; sleep 30; echo 'preStop hook finished'"]
