apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: yolo
spec:
  protocol: v2
  name: yolo
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - name: example
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/video-yolo-pipelines-mlserver:yolo
          name: yolo
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: yolov5m
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
    graph:
      name: yolo
      type: MODEL
      children: []
