apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: facebook-distilbe 
spec:
  name: facebook-distilbe
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines:generalnlp
          name: nlp-1
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: facebook/s2t-small-librispeech-asr
            - name: TRANSFORMERS_CACHE
              value: /app/.cache
            - name: TASK
              value: text-classification
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines:generalnlp
          name: nlp-2
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value:  distilbert-base-uncased-finetuned-sst-2-english
            - name: TRANSFORMERS_CACHE
              value: /app/.cache
            - name: TASK
              value: translation_fr_to_en
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines:generalnlp
          name: nlp-3
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: 
            - name: TRANSFORMERS_CACHE
              value: /app/.cache
            - name: TASK
              value: summarization
    graph:
      name: nlp-1
      type: MODEL
      children:
      - name: nlp-2
        type: MODEL
        children:
        - name: nlp-3
          type: MODEL
          children: []
    name: example
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1