apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: router
spec:
  protocol: v2
  name: router
  # annotations:
  #   seldon.io/engine-separate-pod: "true"
  predictors:
  - name: router
    annotations:
      seldon.io/no-engine: "true" 
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/router:router
          name: router
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 4Gi
            limits:
              cpu: '4'
              memory: 4Gi
          env:
            - name: MODEL_LISTS
              value: '["audio", "nlp-qa"]'
            #   value: automatic-speech-recognition
            # - name: MLSERVER_MODEL_MAX_BATCH_SIZE
            #   value: "1"
            # - name: MLSERVER_MODEL_MAX_BATCH_TIME
            #   value: "1"
            # - name: MLSERVER_PARALLEL_WORKERS
            #   value: "0"
            # - name: USE_THREADING
            #   value: "True"
            # - name: NUM_INTEROP_THREADS
            #   value: "1"
            # - name: NUM_THREADS
            #   value: "1"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    graph:
      name: router
      type: MODEL
      children: []
    svcOrchSpec:
      resources:
        requests:
          cpu: '4'
          memory: 4Gi
        limits:
          cpu: '4'
          memory: 4Gi
      # readinessProbe:
      #   failureThreshold: 3
      #   initialDelaySeconds: 0
      #   periodSeconds: 1
      #   successThreshold: 1
      #   tcpSocket:
      #     port: 9000
      #   timeoutSeconds: 1
    labels:
      sidecar.istio.io/inject: "true"
