apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: sum-qa
spec:
  name: sum-qa
  annotations:
    seldon.io/engine-separate-pod: "true"
  protocol: v2
  predictors:
  - name: sum-qa
    componentSpecs:
    - spec:
        volumes:
        - name: classifier-provision-location
          emptyDir: {}

        initContainers:
        - name: classifier-model-initializer
          image: seldonio/rclone-storage-initializer:1.16.0-dev
          imagePullPolicy: IfNotPresent
          args:
            - "s3://huggingface/summarization/sshleifer-distilbart-cnn-12-6"
            - "/mnt/models/sshleifer-distilbart-cnn-12-6"

          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          envFrom:
          - secretRef:
              name: seldon-rclone-secret

        containers:
        - image: sdghafouri/sum-qa-final:nlpsum
          name: nlp-sum 
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 4Gi
            limits:
              cpu: '4'
          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          env:
            - name: MODEL_VARIANT
              value:  /mnt/models/sshleifer-distilbart-cnn-12-6
            - name: TASK
              value: summarization
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
            - name: USE_THREADING
              value: "True"
            - name: NUM_INTEROP_THREADS
              value: "1"
            - name: NUM_THREADS
              value: "1"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    - spec:

        volumes:
        - name: classifier-provision-location
          emptyDir: {}

        initContainers:
        - name: classifier-model-initializer
          image: seldonio/rclone-storage-initializer:1.16.0-dev
          imagePullPolicy: IfNotPresent
          args:
            - "s3://huggingface/question-answering/distilbert-base-cased-distilled-squad"
            - "/mnt/models/distilbert-base-cased-distilled-squad"

          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          envFrom:
          - secretRef:
              name: seldon-rclone-secret

        containers:
        - image: sdghafouri/sum-qa-final:nlpqa
          name: nlp-qa 
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 4Gi
            limits:
              cpu: '4'
              memory: 4Gi
          volumeMounts:
          - mountPath: /mnt/models
            name: classifier-provision-location

          env:
            - name: MODEL_VARIANT
              value: /mnt/models/distilbert-base-cased-distilled-squad
            - name: TASK
              value: question-answering
            - name: CONTEXT
              value: default
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
            - name: USE_THREADING
              value: "True"
            - name: NUM_INTEROP_THREADS
              value: "1"
            - name: NUM_THREADS
              value: "1"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    graph:
      name: nlp-sum
      type: MODEL
      children:
      - name: nlp-qa
        type: MODEL
        children: []
    svcOrchSpec:
      resources:
        requests:
          cpu: '4'
          memory: 4Gi
        limits:
          cpu: '4'
          memory: 4Gi
    name: example
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1
