apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: audio-qa
spec:
  name: audio-qa
  annotations:
    seldon.io/engine-separate-pod: "true"
  protocol: v2
  predictors:
  - name: audio-qa
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/audio-qa-final:audio
          name: audio
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 6Gi
            limits:
              cpu: '4'
              memory: 6Gi
          env:
            - name: MODEL_VARIANT
              value: facebook/s2t-small-librispeech-asr
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: TASK
              value: automatic-speech-recognition
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "1"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
            - name: USE_THREADING
              value: "True"
            - name: NUM_INTEROP_THREADS
              value: "4"
            - name: NUM_THREADS
              value: "4"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    - spec:
        containers:
        - image: sdghafouri/audio-qa-final:nlpqa
          name: nlp-qa 
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 6Gi
            limits:
              cpu: '4'
              memory: 6Gi
          env:
            - name: MODEL_VARIANT
              value: distilbert-base-uncased
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: TASK
              value: question-answering
            - name: CONTEXT
              value: default
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "1"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "1"
            - name: USE_THREADING
              value: "True"
            - name: NUM_INTEROP_THREADS
              value: "4"
            - name: NUM_THREADS
              value: "4"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    graph:
      name: audio
      type: MODEL
      children:
      - name: nlp-qa
        type: MODEL
        children: []
    svcOrchSpec:
      resources:
        requests:
          cpu: '4'
          memory: 4Gi
        limits:
          cpu: '4'
          memory: 4Gi
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1
