apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: resnet
spec:
  name: default
  predictors:
  - graph:
      implementation: TRITON_SERVER
      logger:
        mode: all
      modelUri: s3://triton-server-new/triton-server-new
      envSecretRefName: seldon-init-container-secret
      name: resnet
      type: MODEL
    componentSpecs:
      - spec:
          containers:
            - name: resnet
              env:
                - name: SAEID
                  value: '4'

    annotations:
        seldon.io/no-engine: "true"
    name: default
    replicas: 1
  protocol: kfserving