apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: image-models
spec:
  name: image-models
  predictors:
  - name: default
    annotations:
      seldon.io/no-engine: "true"  
      # prometheus.io/path: "/metrics" # Annotate this 
    componentSpecs:
    - spec:
        containers:
        - image: nvcr.io/nvidia/tritonserver:21.08-py3
          ports:
            - containerPort: 9000
              protocol: TCP
              name: http
            - containerPort: 9500
              protocol: TCP
              name: grpc
            - containerPort: 8002
              protocol: TCP
              name: nv-metrics # create nvidia-metrics port name
          livenessProbe:
            httpGet:
              path: /v2/health/live
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /v2/health/ready
              port: http                
          args: 
            - "/opt/tritonserver/bin/tritonserver"
            - "--http-port=9000" # override default http port
            - "--grpc-port=9500" # override default grpc port
            - "--metrics-port=8002" # must be different to engine port
            - "--model-repository=models"
            - "--model-control-mode=explicit"
            - "--load-model=*"
          envFrom:
            - secretRef: 
                name: seldon-init-container-secret
          imagePullPolicy: IfNotPresent
          name: image-models
        terminationGracePeriodSeconds: 1
    replicas: 1 
    graph:
      name: image-models 
      type: MODEL
  protocol: v2