apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: node-one
spec:
  protocol: v2
  name: node-one
  predictors:
  - name: node-one
    annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/mock-centralized:node-one
          name: node-one
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 4Gi
            limits:
              cpu: '4'
              memory: 4Gi
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    graph:
      name: node-one
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"
