apiVersion: apps/v1
kind: Deployment
metadata:
  name: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      containers:
      - name: iamge
        image: sdghafouri/simple-image:image-kamran
        imagePullPolicy: Always
        env:
          - name: ITERATIONS
            value: '60'
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 1
        ports:
        - containerPort: 8080
