apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: yolo
spec:
  protocol: v2
  name: yolo
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - name: yolo 
    componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/video-pipelines-mlserver-bytes:yolo
          name: yolo
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '1'
              memory: 4Gi
            limits:
              cpu: '1'
              memory: 4Gi
          env:
            - name: MODEL_VARIANT
              value: yolov5m
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: TORCH_HOME
              value: /opt/mlserver/.torch
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "2"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "0"
            - name: USE_THREADING
              value: "True"
            - name: NUM_INTEROP_THREADS
              value: "5"
            - name: NUM_THREADS
              value: "1"
      replicas: 1
    graph:
      name: yolo
      type: MODEL
      children: []
    svcOrchSpec:
      resources:
        requests:
          cpu: '4'
          memory: 4Gi
        limits:
          cpu: '4'
          memory: 4Gi