apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{podmonitor_name}}
spec:
  selector:
    matchLabels:
      app: {{app_name}}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
  namespaceSelector:
    any: true