
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: video-monitoring-test
spec:
  annotations:
    seldon.io/engine-separate-pod: "true"
  name: video-monitoring-test 
  protocol: v2
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/inferline:video-yolo
          name: video-yolo
          imagePullPolicy: Always
    - spec:
        containers:
        - name: video-resnet-human
    graph:
      name: video-yolo
      type: MODEL
      children:
        - name: video-resnet-human
          type: MODEL
          logger:
            mode: all
          implementation: TRITON_SERVER
          modelUri: s3://separate-servers/separate-servers/resnet
          envSecretRefName: seldon-init-container-secret
          children: []
    name: example
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1
