apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: video-monitoring
spec:
  protocol: v2
  predictors:
    - name: default
      graph:
        name: tokeniser-encoder
        children:
          - name: resnet
            logger:
              mode: all
            implementation: TRITON_SERVER
            modelUri: s3://separate-servers/separate-servers/resnet
            envSecretRefName: seldon-init-container-secret
            children:
              - name: tokeniser-decoder
      componentSpecs:
        - spec:
            containers:
            - name: resnet
        - spec:
            containers:
              - name: tokeniser-encoder
                image: seldonio/gpt2-tokeniser:0.1.0
                env:
                  # Use always a writable HuggingFace cache location regardless of the user
                  - name: TRANSFORMERS_CACHE
                    value: /opt/mlserver/.cache
                  - name: MLSERVER_MODEL_NAME
                    value: "tokeniser-encoder"
        - spec:
            containers:
              - name: tokeniser-decoder
                image: seldonio/gpt2-tokeniser:0.1.0
                env:
                  - name: SELDON_TOKENIZER_TYPE
                    value: "DECODER"
                  # Use always a writable HuggingFace cache location regardless of the user
                  - name: TRANSFORMERS_CACHE
                    value: /opt/mlserver/.cache
                  - name: MLSERVER_MODEL_NAME
                    value: "tokeniser-decoder"