apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: minioadmin
spec:
  name: default
  predictors:
  - graph:
      implementation: TRITON_SERVER
      logger:
        mode: all
      modelUri: minioadmin
      envSecretRefName: seldon-init-container-secret
      name: minioadmin
      type: MODEL
    name: default
    replicas: 1
  protocol: kfserving