apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: yolo
spec:
  name: default
  predictors:
  - graph:
      implementation: TRITON_SERVER
      logger:
        mode: all
      modelUri: s3://separate-servers/separate-servers/yolo
      envSecretRefName: seldon-init-container-secret
      name: yolo
      type: MODEL
    name: default
    replicas: 1
  protocol: kfserving