apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: {{ name }}
spec:
  protocol: v2
  name: {{ name }}
  annotations:
    proxy.istio.io/config: |
      terminationDrainDuration: {{ distrpution_time }}s
  predictors:
  - name: {{ name }}
    annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - spec:

        volumes:
        - name: resnet-volume
          emptyDir: {}

        initContainers:
        - name: classifier-model-initializer
          image: seldonio/rclone-storage-initializer:1.16.0-dev
          imagePullPolicy: IfNotPresent
          args:
            - "s3://torchhub/resnet/{{ model_variant }}"
            - "/opt/mlserver/.torch/hub/checkpoints/"

          volumeMounts:
          - mountPath: /opt/mlserver/.torch/hub/checkpoints
            name: resnet-volume

          envFrom:
          - secretRef:
              name: seldon-rclone-secret

        terminationGracePeriodSeconds: {{ distrpution_time }}
        containers:
        - image: sdghafouri/video-final:resnet-human
          name: resnet-human
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '{{ cpu_request }}'
              memory: '{{ memory_request }}'
            limits:
              cpu: '{{ cpu_limit }}'
              memory: '{{ memory_limit }}'
          volumeMounts:
          - mountPath: /opt/mlserver/.torch/hub/checkpoints
            name: resnet-volume

          env:
            - name: MODEL_VARIANT
              value: {{ model_variant }}
            - name: TORCH_HOME
              value: /opt/mlserver/.torch
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: '{{ max_batch_size }}'
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: '{{ max_batch_time }}'
            - name: MLSERVER_PARALLEL_WORKERS
              value: "0"
            - name: USE_THREADING
              value: '{{use_threading}}'
            - name: NUM_INTEROP_THREADS
              value: '{{num_interop_threads}}'
            - name: NUM_THREADS
              value: '{{num_threads}}'
            - name: LOGS_ENABLED
              value: '{{ logs_enabled }}'
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - /bin/sleep {{ distrpution_time }}
      replicas: {{ replicas }}
    graph:
      name: resnet-human
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"