apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: nlp
spec:
  protocol: v2
  name: nlp
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines-mlserver:nlpli
          name: nlp-li
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: dinalzein/xlm-roberta-base-finetuned-language-identification
            - name: TASK
              value: text-classification
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines-mlserver:nlptrans
          name: nlp-trans
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: Helsinki-NLP/opus-mt-fr-en
            - name: TASK
              value: translation_fr_to_en
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
    - spec:
        containers:
        - image: sdghafouri/nlp-pipelines-mlserver:nlpsum
          name: nlp-sum
          imagePullPolicy: Always
          env:
            - name: MODEL_VARIANT
              value: sshleifer/distilbart-cnn-12-6
            - name: TASK
              value: summarization
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
    graph:
      name: nlp-li
      type: MODEL
      children:
      - name: nlp-trans
        type: MODEL
        children:
        - name: nlp-sum
          type: MODEL
          children: []
    name: example
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1
