apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: test-replicas
spec:
  replicas: 1
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier1
    - spec:
        containers:
        - image: seldonio/mock_classifier_rest:1.3
          name: classifier2
    graph:
      endpoint:
        type: REST
      name: classifier1
      type: MODEL
      children:
      - name: classifier2
        type: MODEL
        endpoint:
          type: REST
    labels:
      sidecar.istio.io/inject: "true"
    name: seldondeployment
