apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: video
spec:
  protocol: v2
  name: video
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - name: video
    componentSpecs:
    - spec:
        volumes:
        - name: yolov5_volume
          emptyDir: {}
        initContainers:
        - name: classifier-model-initializer
          image: seldonio/rclone-storage-initializer:1.16.0-dev
          imagePullPolicy: IfNotPresent
          args:
            - "s3://torchhub/yolov5m"
            - "/mnt/models/yolov5m"
          volumeMounts:
          - mountPath: /mnt/models
            name: yolov5_volume
          envFrom:
          - secretRef:
              name: seldon-rclone-secret
        containers:
        - image: sdghafouri/video-pipelines-mlserver-bytes:yolov5
          name: yolo
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /mnt/models
            name: yolov5_volume
          env:
            - name: MODEL_PATH
              value: /mnt/models/yolov5m
            - name: MODEL_VARIANT
              value: yolov5m
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: TORCH_HOME
              value: /opt/mlserver/.torch
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "0"
            - name: USE_THREADING
              value: "True"
            - name: NUM_INTEROP_THREADS
              value: "1"
            - name: NUM_THREADS
              value: "1"
      replicas: 2
    - spec:
        volumes:
        - name: resnet-volume
          emptyDir: {}
        initContainers:
        - name: classifier-model-initializer
          image: seldonio/rclone-storage-initializer:1.16.0-dev
          imagePullPolicy: IfNotPresent
          args:
            - "s3://torchhub/resnet/resnet18"
            - "/opt/mlserver/.torch/hub/checkpoints/"
          volumeMounts:
          - mountPath: /opt/mlserver/.torch/hub/checkpoints
            name: resnet-volume
          envFrom:
          - secretRef:
              name: seldon-rclone-secret
        containers:
        - image: sdghafouri/video-pipelines-mlserver-bytes:resnet-human
          name: resnet-human
          imagePullPolicy: Always
          volumeMounts:
          - mountPath: /opt/mlserver/.torch/hub/checkpoints
            name: resnet-volume
          env:
            - name: MODEL_VARIANT
              value: resnet18
            - name: TRANSFORMERS_CACHE
              value: /opt/mlserver/.cache
            - name: TORCH_HOME
              value: /opt/mlserver/.torch
            - name: MLSERVER_MODEL_MAX_BATCH_SIZE
              value: "5"
            - name: MLSERVER_MODEL_MAX_BATCH_TIME
              value: "1"
            - name: MLSERVER_PARALLEL_WORKERS
              value: "0"
            - name: USE_THREADING
              value: "True"
            - name: NUM_INTEROP_THREADS
              value: "1"
            - name: NUM_THREADS
              value: "1"
      replicas: 2
    graph:
      name: yolo
      type: MODEL
      children:
      - name: resnet-human
        type: MODEL
        children: []
    svcOrchSpec:
      resources:
        requests:
          cpu: '8'
          memory: 4Gi
        limits:
          cpu: '8'
          memory: 4Gi
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1