apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: router
spec:
  protocol: v2
  name: router
  predictors:
  - name: router
    annotations:
      seldon.io/no-engine: "true" 
    componentSpecs:
    - spec:
        volumes:
        - name: logs-volume
          hostPath:
            path: /home/cc/infernece-pipeline-joint-optimization/data/logs

        containers:
        - image: sdghafouri/router:router-debug
          name: router
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '4'
              memory: 8Gi
            limits:
              cpu: '16'
              memory: 16Gi
          volumeMounts:
          - name: logs-volume
            mountPath: /opt/mlserver/logs
          env:
            - name: MODEL_LISTS
              value: '["queue-one", "queue-two"]'
            - name: MLSERVER_PARALLEL_WORKERS
              value: "0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
      replicas: 1
    graph:
      name: router
      type: MODEL
      children: []
    labels:
      sidecar.istio.io/inject: "true"
