
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: inferline-cascade
spec:
  name: inferline-cascade
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/inferline:cascade-inception
          name: cascade-inception
          imagePullPolicy: Always
    - spec:
        containers:
        - image: sdghafouri/inferline:cascade-resnet
          name: cascade-resnet
          imagePullPolicy: Always
    - spec:
        containers: 
        - image: sdghafouri/inferline:cascade-combiner
          name: cascade-combiner
          imagePullPolicy: Always
    graph:
      name: cascade-combiner
      type: COMBINER
      children:
      - name: cascade-resnet
        type: MODEL
        children: []
      - name: cascade-inception 
        type: MODEL
        children: [] 
    name: example
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1
