apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: inferline-cascade
spec:
  name: inferline-cascade
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/inferline:cascade-resnet
          name: cascade-resnet
          imagePullPolicy: Always
    - spec:
        containers:
        - image: sdghafouri/inferline:router
          name: cascade-router
          imagePullPolicy: Always
    graph:
      name: cascade-resnet
      type: MODEL
      children:
        - name: cascade-router
          type: ROUTER
    labels:
      sidecar.istio.io/inject: "true"
    name: example
