apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: inferline-cascade
spec:
  name: inferline-cascade
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/inferline:cascade-inception
          name: cascade-inception
          imagePullPolicy: Always
    graph:
      name: cascade-inception
      type: MODEL
    labels:
      sidecar.istio.io/inject: "true"
    name: example
