apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: inferline
spec:
  name: inferline
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/inferline:cascade-resnet
          name: node-one
          imagePullPolicy: Always
    graph:
      name: node-one
      type: MODEL
    labels:
      sidecar.istio.io/inject: "true"
    name: example
