apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: linear-pipeline-separate-pods
spec:
  name: linear-pipeline
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/linearmodel:nodeone
          name: node-one
          imagePullPolicy: Always
    - spec:
        containers:
        - image: sdghafouri/linearmodel:nodetwo
          name: node-two
          imagePullPolicy: Always
    - spec:
        containers:
          - image: sdghafouri/linearmodel:nodethree
            name: node-three
            imagePullPolicy: Always
    graph:
      name: node-one
      type: MODEL
      children:
      - name: node-two
        type: MODEL
        children:
        - name: node-three
          type: MODEL
          children: []
    labels:
      sidecar.istio.io/inject: "true"
    name: example
