apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: seldon-core
    seldon-app: resnet-human-resnet-human
    seldon-deployment-id: resnet-human
    seldon.io/model: "true"
  name: resnet-human-resnet-human
  namespace: default
spec:
  clusterIP: 10.152.183.189
  clusterIPs:
  - 10.152.183.189
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: grpc
    port: 9500
    protocol: TCP
    targetPort: 9500
  selector:
    seldon-app: resnet-human-resnet-human
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
