apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: seldon-core
    seldon-app: queue-resnet-human-queue-resnet-human
    seldon-deployment-id: queue-resnet-human
    seldon.io/model: "true"
  name: queue-resnet-human-queue-resnet-human
  namespace: default
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: grpc
    port: 9500
    protocol: TCP
    targetPort: 9500
  selector:
    seldon-app: queue-resnet-human-queue-resnet-human
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
