
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: inferline-video
spec:
  name: inferline-video
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - image: sdghafouri/inferline:video-yolo
          name: video-yolo
          imagePullPolicy: Always
    - spec:
        containers:
        - image: sdghafouri/inferline:video-resnet-human
          name: resnet
          imagePullPolicy: Always
          env:
            - name: WITH_PREPROCESSOR
              value: 'False'
    graph:
      name: video-yolo
      type: MODEL
      children: []
    name: example
    labels:
      sidecar.istio.io/inject: "true"
    replicas: 1
