apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: resnet-car-resnet-car-0-resnet-car
    app.kubernetes.io/managed-by: seldon-core
    fluentd: "true"
    seldon-app: resnet-car-resnet-car
    seldon-app-svc-resnet-car: resnet-car-resnet-car-resnet-car
    seldon-deployment-id: resnet-car
    seldon.io/model: "true"
    sidecar.istio.io/inject: "true"
    version: resnet-car
  name: resnet-car-resnet-car-0-resnet-car
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      seldon-app: resnet-car-resnet-car
      seldon-app-svc-resnet-car: resnet-car-resnet-car-resnet-car
      seldon-deployment-id: resnet-car
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /prometheus
        prometheus.io/scrape: "true"
        seldon.io/no-engine: "true"
      creationTimestamp: null
      labels:
        app: resnet-car-resnet-car-0-resnet-car
        app.kubernetes.io/managed-by: seldon-core
        fluentd: "true"
        seldon-app: resnet-car-resnet-car
        seldon-app-svc-resnet-car: resnet-car-resnet-car-resnet-car
        seldon-deployment-id: resnet-car
        seldon.io/model: "true"
        sidecar.istio.io/inject: "true"
        version: resnet-car
    spec:
      containers:
      - env:
        - name: MODEL_VARIANT
          value: resnet18
        - name: TORCH_HOME
          value: /opt/mlserver/.torch
        - name: MLSERVER_MODEL_MAX_BATCH_SIZE
          value: "1"
        - name: MLSERVER_MODEL_MAX_BATCH_TIME
          value: "1"
        - name: MLSERVER_PARALLEL_WORKERS
          value: "0"
        - name: USE_THREADING
          value: "True"
        - name: NUM_INTEROP_THREADS
          value: "4"
        - name: NUM_THREADS
          value: "4"
        - name: LOGS_ENABLED
          value: "True"
        - name: PREDICTIVE_UNIT_SERVICE_PORT
          value: "9000"
        - name: PREDICTIVE_UNIT_HTTP_SERVICE_PORT
          value: "9000"
        - name: MLSERVER_HTTP_PORT
          value: "9000"
        - name: PREDICTIVE_UNIT_GRPC_SERVICE_PORT
          value: "9500"
        - name: MLSERVER_GRPC_PORT
          value: "9500"
        - name: PREDICTIVE_UNIT_ID
          value: resnet-car
        - name: MLSERVER_MODEL_NAME
          value: resnet-car
        - name: PREDICTIVE_UNIT_IMAGE
          value: sdghafouri/dynainf:resnet-car
        - name: PREDICTOR_ID
          value: resnet-car
        - name: PREDICTOR_LABELS
          value: '{"sidecar.istio.io/inject":"true","version":"resnet-car"}'
        - name: SELDON_DEPLOYMENT_ID
          value: resnet-car
        - name: SELDON_EXECUTOR_ENABLED
          value: "true"
        - name: PREDICTIVE_UNIT_METRICS_SERVICE_PORT
          value: "6000"
        - name: PREDICTIVE_UNIT_METRICS_ENDPOINT
          value: /prometheus
        - name: MLSERVER_METRICS_PORT
          value: "6000"
        - name: MLSERVER_METRICS_ENDPOINT
          value: /prometheus
        image: sdghafouri/dynainf:resnet-car
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - /bin/sleep 10
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 1
        name: resnet-car
        ports:
        - containerPort: 6000
          name: metrics
          protocol: TCP
        - containerPort: 9000
          name: http
          protocol: TCP
        - containerPort: 9500
          name: grpc
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 1
          successThreshold: 1
          tcpSocket:
            port: 9000
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: "4"
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/mlserver/.torch/hub/checkpoints
          name: resnet-volume
        - mountPath: /etc/podinfo
          name: seldon-podinfo
      dnsPolicy: ClusterFirst
      initContainers:
      - args:
        - s3://torchhub/resnet/resnet18
        - /opt/mlserver/.torch/hub/checkpoints/
        envFrom:
        - secretRef:
            name: seldon-rclone-secret
        image: seldonio/rclone-storage-initializer:1.16.0-dev
        imagePullPolicy: IfNotPresent
        name: classifier-model-initializer
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/mlserver/.torch/hub/checkpoints
          name: resnet-volume
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 8888
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: resnet-volume
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: seldon-podinfo
