apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: seldon-core
    seldon-app: resnet-car-resnet-car
    seldon-app-svc-resnet-car: resnet-car-resnet-car-resnet-car
    seldon-deployment-id: resnet-car
    seldon.io/model: "true"
  name: resnet-car-resnet-car-resnet-car
  namespace: default
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: grpc
    port: 9500
    protocol: TCP
    targetPort: 9500
  selector:
    seldon-app-svc-resnet-car: resnet-car-resnet-car-resnet-car
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
