apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: yolo
  namespace: default
spec:
  annotations:
    proxy.istio.io/config: |
      terminationDrainDuration: 30s
  name: yolo
  predictors:
  - annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - replicas: 5
      spec:
        containers:
        - env:
          - name: MODEL_PATH
            value: /mnt/models/yolov5n
          - name: MODEL_VARIANT
            value: yolov5n
          - name: TORCH_HOME
            value: /opt/mlserver/.torch
          - name: MLSERVER_PARALLEL_WORKERS
            value: "0"
          - name: USE_THREADING
            value: "True"
          - name: NUM_INTEROP_THREADS
            value: "1"
          - name: NUM_THREADS
            value: "1"
          - name: DROP_LIMIT
            value: "10000"
          image: sdghafouri/video-centralized:yolo
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - /bin/sleep 30
          name: yolo
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
          - mountPath: /mnt/models
            name: yolov5-volume
        initContainers:
        - args:
          - s3://torchhub/yolo/yolov5n
          - /mnt/models/yolov5n
          envFrom:
          - secretRef:
              name: seldon-rclone-secret
          image: seldonio/rclone-storage-initializer:1.16.0-dev
          imagePullPolicy: IfNotPresent
          name: classifier-model-initializer
          volumeMounts:
          - mountPath: /mnt/models
            name: yolov5-volume
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: yolov5-volume
    graph:
      children: []
      name: yolo
      type: MODEL
    labels:
      sidecar.istio.io/inject: "true"
    name: yolo
  protocol: v2

---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  annotations:
  name: resnet-human
  namespace: default
spec:
  annotations:
    proxy.istio.io/config: |
      terminationDrainDuration: 30s
  name: resnet-human
  predictors:
  - annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - replicas: 2
      spec:
        containers:
        - env:
          - name: MODEL_VARIANT
            value: resnet18
          - name: TORCH_HOME
            value: /opt/mlserver/.torch
          - name: MLSERVER_PARALLEL_WORKERS
            value: "0"
          - name: USE_THREADING
            value: "True"
          - name: NUM_INTEROP_THREADS
            value: "1"
          - name: NUM_THREADS
            value: "1"
          - name: DROP_LIMIT
            value: "10000"
          image: sdghafouri/video-centralized:resnet-human
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - /bin/sleep 30
          name: resnet-human
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "1"
              memory: 2Gi
          volumeMounts:
          - mountPath: /opt/mlserver/.torch/hub/checkpoints
            name: resnet-volume
        initContainers:
        - args:
          - s3://torchhub/resnet/resnet18
          - /opt/mlserver/.torch/hub/checkpoints/
          envFrom:
          - secretRef:
              name: seldon-rclone-secret
          image: seldonio/rclone-storage-initializer:1.16.0-dev
          imagePullPolicy: IfNotPresent
          name: classifier-model-initializer
          volumeMounts:
          - mountPath: /opt/mlserver/.torch/hub/checkpoints
            name: resnet-volume
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: resnet-volume
    graph:
      children: []
      name: resnet-human
      type: MODEL
    labels:
      sidecar.istio.io/inject: "true"
    name: resnet-human
  protocol: v2

---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  annotations:
  name: queue-yolo
  namespace: default
spec:
  annotations:
    proxy.istio.io/config: |
      terminationDrainDuration: 120s
  name: queue-yolo
  predictors:
  - annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - replicas: 1
      spec:
        containers:
        - env:
          - name: MODEL_NAME
            value: yolo
          - name: LAST_NODE
            value: "False"
          - name: MLSERVER_MODEL_MAX_BATCH_SIZE
            value: "1"
          - name: MLSERVER_MODEL_MAX_BATCH_TIME
            value: "1"
          - name: MLSERVER_PARALLEL_WORKERS
            value: "0"
          - name: DROP_LIMIT
            value: "10000"
          image: sdghafouri/queue:queue
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - /bin/sleep 120
          name: queue-yolo
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "16"
              memory: 16Gi
            requests:
              cpu: "4"
              memory: 8Gi
        terminationGracePeriodSeconds: 120
    graph:
      children: []
      name: queue-yolo
      type: MODEL
    labels:
      sidecar.istio.io/inject: "true"
    name: queue-yolo
  protocol: v2

---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  annotations:
  name: queue-resnet-human
  namespace: default
spec:
  annotations:
    proxy.istio.io/config: |
      terminationDrainDuration: 120s
  name: queue-resnet-human
  predictors:
  - annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - replicas: 1
      spec:
        containers:
        - env:
          - name: MODEL_NAME
            value: resnet-human
          - name: LAST_NODE
            value: "False"
          - name: MLSERVER_MODEL_MAX_BATCH_SIZE
            value: "16"
          - name: MLSERVER_MODEL_MAX_BATCH_TIME
            value: "1"
          - name: MLSERVER_PARALLEL_WORKERS
            value: "0"
          - name: DROP_LIMIT
            value: "10000"
          image: sdghafouri/queue:queue
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - /bin/sleep 120
          name: queue-resnet-human
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "16"
              memory: 16Gi
            requests:
              cpu: "4"
              memory: 8Gi
        terminationGracePeriodSeconds: 120
    graph:
      children: []
      name: queue-resnet-human
      type: MODEL
    labels:
      sidecar.istio.io/inject: "true"
    name: queue-resnet-human
  protocol: v2

---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  annotations:
  name: router
  namespace: default
spec:
  annotations:
    proxy.istio.io/config: |
      terminationDrainDuration: 30s
  name: router
  predictors:
  - annotations:
      seldon.io/no-engine: "true"
    componentSpecs:
    - replicas: 1
      spec:
        containers:
        - env:
          - name: MODEL_LISTS
            value: '["queue-yolo", "queue-resnet-human"]'
          - name: MLSERVER_PARALLEL_WORKERS
            value: "8"
          - name: DROP_LIMIT
            value: "10000"
          image: sdghafouri/router:router
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - /bin/sh
                - -c
                - /bin/sleep 30
          name: router
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 1
            successThreshold: 1
            tcpSocket:
              port: 9000
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "16"
              memory: 16Gi
            requests:
              cpu: "4"
              memory: 8Gi
        terminationGracePeriodSeconds: 30
    graph:
      children: []
      name: router
      type: MODEL
    labels:
      sidecar.istio.io/inject: "true"
    name: router
  protocol: v2

